messages/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to

from django_messages.views import *
from messages.forms import MyComposeForm

urlpatterns = patterns('',
    url(r'^$', redirect_to, {'url': 'inbox/'}, name='messages_redirect'),
    url(r'^inbox/$', inbox, name='messages_inbox'),
    url(r'^outbox/$', outbox, name='messages_outbox'),
    url(r'^compose/$', compose, {'form_class':MyComposeForm}, name='messages_compose'),
    url(r'^compose/(?P<recipient>[\w.@+-]+)/$', compose, name='messages_compose_to'),
    url(r'^reply/(?P<message_id>[\d]+)/$', reply, name='messages_reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', view, name='messages_detail'),
    url(r'^delete/(?P<message_id>[\d]+)/$', delete, name='messages_delete'),
    url(r'^undelete/(?P<message_id>[\d]+)/$', undelete, name='messages_undelete'),
    url(r'^trash/$', trash, name='messages_trash'),
)

location/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from gmapi.forms.widgets import GoogleMap
from location.models import Activity, Location, Skill, Province

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field, Fieldset, MultiField, HTML
from crispy_forms.bootstrap import FormActions

import re

class MyInfoForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Field('email'),
            Field('first_name', css_class='input-xlarge'),
            Field('last_name', css_class='input-xlarge'),
            Field('skills', style="background: #FAFAFA; padding: 10px;"),
            Field('other_skills', css_class='input-xlarge'),
            FormActions(
                Submit('save', _('Save'), css_class="btn btn-primary"),
            )
        )        
        super(MyInfoForm, self).__init__(*args, **kwargs)

    email = forms.CharField(label=_('E-mail'), max_length=50, 
        widget=forms.HiddenInput())
    first_name = forms.CharField(label=_('First name'), max_length=50)
    last_name = forms.CharField(label=_('Last name'), max_length=50)
    skills = forms.ModelMultipleChoiceField(
        label=_('Skill'),
        required=False,
        queryset=Skill.objects.all(), 
        widget=forms.widgets.CheckboxSelectMultiple()
    )
    other_skills = forms.CharField(required=False, label=_('Other skills'), max_length=200)

class UserForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Field('email'),
            Field('old_password', css_class='input-xlarge'),
            Field('new_password1', css_class='input-xlarge'),
            Field('new_password2', css_class='input-xlarge'),
            FormActions(
                Submit('save', _('Save'), css_class="btn btn-primary"),
            )
        )        
        super(UserForm, self).__init__(*args, **kwargs) 

    email = forms.CharField(label=_('E-mail'), max_length=50, 
        widget=forms.HiddenInput())
                
    old_password = forms.CharField(required=False,
        label=_('Password'), widget=forms.PasswordInput()
    )
    
    new_password1 = forms.CharField(required=False,
        label=_('New password'), widget=forms.PasswordInput()
    )

    new_password2 = forms.CharField(required=False,
        label=_('New password (again)'), widget=forms.PasswordInput()
    )
    
    def clean_old_password(self):
        email = self.cleaned_data['email']
        password = self.cleaned_data['old_password']
        if authenticate(email=email, password=password):
            return password
        raise forms.ValidationError(_('Wrong password'))
        
    def clean_new_password2(self):
        if 'new_password1' in self.cleaned_data or 'new_password2' in self.cleaned_data:
            password1 = self.cleaned_data['new_password1']
            password2 = self.cleaned_data['new_password2']
            if password1 == password2:
                return password2
            raise forms.ValidationError(_('Password do not match'))        
        
class RegistrationForm(forms.Form):
    
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Field('first_name', css_class='input-xlarge'),
            Field('last_name', css_class='input-xlarge'),
            Field('email', css_class='input-xlarge'),
            Field('password1', css_class='input-xlarge'),
            Field('password2', css_class='input-xlarge'),
            FormActions(
                Submit('register', _('Register'), css_class="btn btn-primary"),
            )
        )
        super(RegistrationForm, self).__init__(*args, **kwargs)
        
    first_name = forms.CharField(label=_('First name'), max_length=50)
    last_name = forms.CharField(label=_('Last name'), max_length=50)
    email = forms.EmailField(label=_('E-mail'))
    password1 = forms.CharField(
        label=_('Password'), widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        label=_('Password (again)'), widget=forms.PasswordInput()
    )
    
    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
            raise forms.ValidationError(_('Password do not match'))
            
    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError(_('E-mail is already taken.'))
        
class MapForm(forms.Form):
    gmap = forms.Field(widget=GoogleMap(attrs={'width':800, 'height':580, 'nojquery':True}))
    
class SearchMapForm(forms.Form):
    gmap = forms.Field(widget=GoogleMap(attrs={'width':400, 'height':400, 'nojquery':True}))

class SearchMapPhoneForm(forms.Form):
    gmap = forms.Field(widget=GoogleMap(attrs={'width':280, 'height':280, 'nojquery':True}))
    
class LocationForm(ModelForm):

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Field('place_name', css_class='input-xlarge'),
            Field('status', css_class='input-xlarge'),            
            Field('organization', css_class='input-xlarge'),
            Field('relation', css_class='input-xlarge'),
            Field('phone_number', css_class='input-xlarge'),
            Field('address', rows="4", css_class='input-xlarge'),
            Div('hide_email', 'hide_phone_number', 'hide_address', css_class="privacy_info"),
            Field('city', css_class='input-xlarge'),
            Field('country', css_class='input-xlarge'),
            Field('latitude', css_class='input-xlarge'),
            Field('longitude', css_class='input-xlarge'),   
            HTML(""" 
            <div id="div_id_map" class="control-group">
                {% load i18n %}
                <label for="div_id_map" class="control-label">
                    {% trans 'Map' %}
                </label>
                <div class="controls">
                    <input type="text" class="input-medium search-query" placeholder="{% trans 'Find your location' %}">
                    <button type="button" class="btn" onClick="search($('.search-query').val());">{% trans 'Search' %}</button>
                    {{ map_form.media.js }}    
                    <p>{{ map_form.gmap }}</p>
                    <p id="hint_id_map" class="help-block"></p>
                    <p class="text-warning">
                        {% trans 'Drag and drop the marker to pinpoint the place.' %}
                    </p>                    
                </div>
            </div>
            """),
            Field('activities', style="background: #FAFAFA; padding: 10px;"),
            Field('additional_info', rows="8", css_class='input-xlarge'),
            FormActions(
                Submit('save', _('Save'), css_class="btn btn-primary"),
            )
        )        
        super(LocationForm, self).__init__(*args, **kwargs)
        self.fields['activities'].label = _('Activities')
        self.fields['latitude'].label = _('Latitude')
        self.fields['longitude'].label = _('Longitude')
    
    class Meta:
        model = Location
        fields = (
            'status', 'organization', 'relation',
            'place_name', 'longitude', 'latitude', 
            'address', 'phone_number',
            'hide_email', 'hide_phone_number', 'hide_address',
            'activities', 'additional_info', 'city', 'country')
        widgets = {
            'address': forms.Textarea(attrs={'rows':4, 'cols':40}),
        }
        
    additional_info = forms.CharField(
        label=_('Additional information'),
        required=False,
        widget=forms.Textarea(attrs={'rows':8, 'cols':40, 
            'placeholder':_('If you want to request the Dhamma media, please use the another channel.')}),
        help_text=_('<p class="text-warning">If you want Dhamma media or have suggestion,'
        ' Please click'
        ' <a class="btn btn-success" href="https://spreadsheets.google.com/viewform?formkey=dFRRZ3djOVVVX3IxYTExUEZDamI3enc6MQ">this button</a>.</p>')
    )
    
    city = forms.CharField(        
        widget=forms.widgets.Select(
            choices=map(lambda x: (x.name, x.name),Province.objects.all())
        )
    )    
    latitude = forms.FloatField(max_value=90, min_value=-90)
    longitude = forms.FloatField(max_value=180, min_value=-180, 
        help_text=_('<p class="text-warning">Please use the map to locate your place.</p>')
    )
    activities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Activity.objects.order_by('-priority').all(), 
        widget=forms.widgets.CheckboxSelectMultiple()
    )

templates/add_location_page.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Add place" %}{% endblock %}
{% block head %}{% trans "Add place" %}{% endblock %}
{% block content %}


  <div id="lat_lng_modal" class="modal hide fade">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4>{% trans "You don't specific your location yet." %}</h4>
    </div>
    <div class="modal-body">
      <p>{% trans "Please use the map to locate your place." %}</p>
    </div>
    <div class="modal-footer">
      <a href="#" data-dismiss="modal" aria-hidden="true" class="btn">Close</a>
    </div>
  </div>

<script type="text/javascript">
  $(".alert").hide();
  $(document).ready(function() {
    $('#submit-id-save').click(function(event) {      
      var lat = $('#id_latitude').val();
      var lng = $('#id_longitude').val();
      if (lat == '15.87003' && lng == '100.99254') {
        event.preventDefault();
        $('#lat_lng_modal').modal();
      }
    });
  });
</script>
{% include 'location_content.html' %}

{% endblock %}

templates/base.html
{% load l10n %}
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>
      Buddhawajana Institution | {% block title %}{% endblock %}
    </title>
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no" />
    <link rel="stylesheet" href="{{STATIC_URL}}css/style.css" type="text/css"/>
    <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap.css" type="text/css"/>
    <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap-responsive.css" type="text/css"/>
    <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap-image-gallery.css" type="text/css"/>
    <link rel="stylesheet" href="{{STATIC_URL}}file_upload/css/jquery.fileupload-ui.css" type="text/css"/>
    <link rel="stylesheet" href="{{STATIC_URL}}css/back_to_top.css" type="text/css"/>    
    <style type="text/css">
      .nav, .nav-header {
        font-size: 19px;
      }
    </style>
    <script type="text/javascript" src="{{STATIC_URL}}js/jquery.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}waypoints/js/waypoints.min.js"></script> 
    <script type="text/javascript" src="{{STATIC_URL}}angular/angular.min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}angular/angular-resource.min.js"></script>
    <script type="text/javascript">
        
      angular.module('app', ['ngResource'])
      .config(['$interpolateProvider', function ($interpolateProvider) {
        $interpolateProvider.startSymbol('<[');
        $interpolateProvider.endSymbol(']>');
      }])    
      .directive('myRepeatDirective', function() {
        return function(scope, element, attrs) {
          if (scope.$last){
            jQuery("a.location").click(function(event) {
              event.preventDefault();
            });
          }
        };
      })
      .factory('Nav', function($resource) {
        var Nav = $resource('/navs/');
        return Nav;
      });
          
      function set_map_type(map_type) {
        $.post("/set_map_type/", {"map_type":map_type}, function(data) {
          location.reload();
        });
      }
      
      function set_sorting(sorting) {
        $.post("/set_sorting/", {"sorting":sorting}, function(data) {
          location.reload();
        });
      }
       
      $(document).ready(function() {
        var map_menu = $('#top_menu>li').first();
        var saved_class = map_menu.attr('class');
        map_menu.attr('class', $('.btn-navbar').is(':visible') ? 'active' : saved_class);
        
        $(window).resize(function() {
          map_menu.attr('class', $('.btn-navbar').is(':visible') ? 'active' : saved_class);
        });
        
        $('#en_btn').click(function(e) {
          $('#language').val('en');
        });

        $('#th_btn').click(function(e) {
          $('#language').val('th');
        });
        
        $('#road_opt>a').click(function(e) {          
          $('a>i').attr('class', '');
          $('#road_opt>a>i').attr('class', 'icon-ok');
          set_map_type('ROADMAP');
        });

        $('#terrain_opt>a').click(function(e) {
          $('a>i').attr('class', '');
          $('#terrain_opt>a>i').attr('class', 'icon-ok');
          set_map_type('TERRAIN');          
        });

        $('#satellite_opt>a').click(function(e) {
          $('a>i').attr('class', '');
          $('#satellite_opt>a>i').attr('class', 'icon-ok');
          set_map_type('SATELLITE');          
        });

        $('#hybrid_opt>a').click(function(e) {
          $('a>i').attr('class', '');
          $('#hybrid_opt>a>i').attr('class', 'icon-ok');
          set_map_type('HYBRID');          
        });

        $('#entry_sort>a').click(function(e) {
          $('a>i').attr('class', '');
          $('#entry_sort>a>i').attr('class', 'icon-ok');
          set_sorting('entry');          
        });

        $('#alpha_sort>a').click(function(e) {
          $('a>i').attr('class', '');
          $('#alpha_sort>a>i').attr('class', 'icon-ok');
          set_sorting('city');          
        });

      });
    </script>
    <!-- Piwik -->
    <script type="text/javascript">
      var _paq = _paq || [];
      _paq.push(["trackPageView"]);
      _paq.push(["enableLinkTracking"]);

      (function() {
        var u=(("https:" == document.location.protocol) ? "https" : "http") + "://watnapahpong.com:8079/analytics/";
        _paq.push(["setTrackerUrl", u+"piwik.php"]);
        _paq.push(["setSiteId", "2"]);
        var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
        g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
      })();
    </script>
    <!-- End Piwik Code -->    
    
    {% block script %}{% endblock %}      
  </head>
  <body>    
    
    <div id="logout_alert" class="modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>{% trans 'Logout confirmation' %}</h3>
      </div>
      <div class="modal-body">
        <p>{% trans 'Do you want to logout?' %}</p>
      </div>
      <div class="modal-footer">
        <a data-dismiss="modal" aria-hidden="true" class="btn">{% trans 'Cancel' %}</a>
        <a href="/logout/" class="btn btn-primary">{% trans 'Logout' %}</a>
      </div>
    </div>
    
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">{% trans 'Buddhawajana Network' %}</a>
          <div class="nav-collapse collapse">           
            <ul id="top_menu" class="nav">
              <li class="{% if active_menu == 0 %}active{% else %}{% endif %}">
                <a href="/">{% trans 'Map' %}</a>
              </li>              
              {% if user.is_authenticated %}
                <li class="{% if active_menu == 1 %}active{% else %}{% endif %}">
                  <a href="/places/">{% trans 'My places' %}</a>
                </li>
                <li class="{% if active_menu == 2 %}active{% else %}{% endif %}">
                  <a href="/my_info/">{% trans 'My info' %}</a>
                </li>
                <li class="{% if active_menu == 3 %}active{% else %}{% endif %}">
                  <a href="/members/">{% trans 'Members' %}</a>
                </li>
                <li class="{% if active_menu == 4 %}active{% else %}{% endif %}">
                  <a href="/user_manual/">{% trans 'User manual' %}</a>
                </li>                
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" 
                    data-toggle="dropdown">{% trans "Options" %}<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li class="nav-header">{% trans "Map type" %}</li>                    
                    <li id="road_opt"><a href="#">{% trans "Road" %} <i class="{% if map_type == 'ROADMAP' %}icon-ok{% else %}{% endif %}"></i></a></li>
                    <li id="terrain_opt"><a href="#">{% trans "Terrain" %} <i class="{% if map_type == 'TERRAIN' %}icon-ok{% else %}{% endif %}"></i></a></li>
                    <li id="satellite_opt"><a href="#">{% trans "Satellite" %} <i class="{% if map_type == 'SATELLITE' %}icon-ok{% else %}{% endif %}"></i></a></li>
                    <li id="hybrid_opt"><a href="#">{% trans "Satellite & Labels" %} <i class="{% if map_type == 'HYBRID' %}icon-ok{% else %}{% endif %}"></i></a></li>
                    <li class="nav-header">{% trans "Sorting" %}</li>
                    <li id="entry_sort"><a href="#">{% trans "Entry order" %} <i class="{% if sorting == 'entry' %}icon-ok{% else %}{% endif %}"></i></a></li>
                    <li id="alpha_sort"><a href="#">{% trans "City/Place alphabet" %} <i class="{% if sorting == 'city' %}icon-ok{% else %}{% endif %}"></i></a></li>
                  </ul>
                </li>              
                <li>                  
                  <a href="#" data-toggle="modal" data-target="#logout_alert">{% trans 'Logout' %}</a>
                </li>
              {% else %}
                <li class="{% if active_menu == 1 %}active{% else %}{% endif %}">
                  <a href="/register/">{% trans 'Register' %}</a>
                </li>
                <li class="{% if active_menu == 2 %}active{% else %}{% endif %}">
                  <a href="/user_manual/">{% trans 'User manual' %}</a>
                </li>                
              {% endif %}                            
            </ul>
            <form class="navbar-form pull-right" 
              action="{% url django.views.i18n.set_language %}" method="post">{% csrf_token %}
              <div class="btn-group">
                <input style="height:32px;" id="th_btn" type="submit" class="btn" value="TH"/>
                <input style="height:32px;" id="en_btn" type="submit" class="btn" value="EN"/>
              </div>
              <input id="language" name="language" value="en" type="hidden" />
              <input name="next" type="hidden" value="{{ redirect_to }}" />
            </form>
            {% if not user.is_authenticated %}                        
            <form style="margin-right:20px;" class="navbar-form pull-right" 
              method="POST" action="/login/">{% csrf_token %}
              <input name="email" class="span2" type="text" placeholder={% trans 'Email' %} />
              <input type="hidden" name="this_is_the_login_form" value="1" />
              <input name="password" class="span2" type="password" placeholder={% trans 'Password' %} />
              <button type="submit" class="btn">{% trans 'Login' %}</button>
              <span><a class="btn btn-danger" href="{% url admin_password_reset %}">{%trans 'Forgot password?' %}</a></span>
            </form>
            {% endif %}
            {% if user.is_authenticated %}
              <p style="margin-right:20px;" class="navbar-text pull-right">
                <a href="/edit_user/" class="navbar-link">{{user.email}}</a>
              </p>
            {% endif %}            
          </div>
        </div>        
      </div>      
    </div>   

      
    <div class="container">
      {% if alert_type %}
        <div class="alert {{ alert_type }} fade in">
          <a class="close" data-dismiss="alert">&#215;</a>
          <h4> {{ alert_message }}</h4>
        </div>
      {% endif %}

      {% if not user.is_phone %}
      <div class="page-header row-fluid">
        <div class="span8 pull-left span12-tablet">
          <h1 class="media-heading" style="height:80px; line-height: 80px;">            
      {% else %}
      <h4 style="margin-top:0px;">
      {% endif %}
      {% block head %}{% endblock %}
      {% if not user.is_phone %}
          </h1>
        </div>
        <div class="span4 pull-right hidden-phone hidden-tablet">
          <a href="#">
            <img class="media-object" src="{{STATIC_URL}}images/logo_header.png">              
          </a>
        </div>
      </div>              
      {% else %}
      </h4>
      {% endif %}
      {% block content %}{% endblock %}
    </div>

    <div id="space">&nbsp;</div>
    
    {% block footer %}{% endblock %}      

  </body>
</html>

templates/edit_user_page.html
{% extends "base.html" %}
{% load l10n %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}{% trans "Change password" %}{% endblock %}
{% block head %}{% trans "Change password" %}{% endblock %}
{% block content %}
  {% crispy form %}
{% endblock %}
{% block footer %}{% include "footer.html" %}{% endblock %}

templates/export_page.html
{% extends "base.html" %}
{% load l10n %}
{% load i18n %}
{% block title %}{% trans "Export" %}{% endblock %}
{% block head %}{% trans "Export" %}{% endblock %}
{% block content %}
<form method="post">{% csrf_token %}
  <fieldset>
    <legend>Select fields</legend>

    <label class="checkbox">
      <input type="checkbox" value="1" name="id"> ID
    </label>
    
    <label class="checkbox">
      <input type="checkbox" value="1" name="name"> Name
    </label>

    <label class="checkbox">
      <input type="checkbox" value="1" name="email"> Email
    </label>

    <label class="checkbox">
      <input type="checkbox" value="1" name="phone"> Phone number
    </label>

    <label class="checkbox">
      <input type="checkbox" value="1" name="address"> Address
    </label>

    <label class="checkbox">
      <input type="checkbox" value="1" name="country"> Country
    </label>

    <label class="checkbox">
      <input type="checkbox" value="1" name="city"> City
    </label>
    
    <label class="checkbox">
      <input type="checkbox" value="1" name="skills"> Skills
    </label>

    <label class="checkbox">
      <input type="checkbox" value="1" name="place_name"> Place name
    </label>

    <label class="checkbox">
      <input type="checkbox" value="1" name="geolocation"> Geolocation
    </label>

    <label class="checkbox">
      <input type="checkbox" value="1" name="organization"> Organization
    </label>

    <label class="checkbox">
      <input type="checkbox" value="1" name="status"> Status
    </label>

    <br/>
    <button type="submit" class="btn">Download</button>
  </fieldset>
</form>
{% endblock %}
{% block footer %}{% include "footer.html" %}{% endblock %}

templates/footer.html
<div id="footer" class="muted credit">
  <div class="container" style="vertical-align: middle; margin-top:auto; margin-bottom:auto;">
    COPYRIGHT © 2012 Sutee Sudprasert All rights reserved.
  </div>        
</div>

templates/location_content.html
{% load l10n %}
{% load i18n %}
{% load crispy_forms_tags %}

<script type="text/javascript">
  $(".alert").hide();
  $(document).ready(function() {
    $('#submit-id-save').click(function(event) {      
      var lat = $('#id_latitude').val();
      var lng = $('#id_longitude').val();
      if (lat == '15.87003' && lng == '100.99254') {
        event.preventDefault();
        $('#lat_lng_modal').modal();
      }
    });
  });
</script>

<script type="text/javascript">
  $(document).ready(function() {
    var is_organization = $('#id_organization').is(':checked');
    if (!is_organization) {
      $('#div_id_relation').hide()
    }
    
    $('#id_organization').click(function() {
      if($(this).is(':checked')) {
        $('#div_id_relation').show();
      } else {
        $('#div_id_relation').hide();
      }
    });
    
  });
</script>


<div id="alert_not_found" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>{% trans 'Search Result' %}</h3>
  </div>
  <div class="modal-body">
    <p id="alert_text"></p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">{% trans "Close" %}</a>
  </div>
</div>

<div class="row">
  <div class="span12">
    {% crispy form %}
  </div>
</div>

<script type="text/javascript">

  function setup_foreign_city() {
    var city = '{{ form.city.value }}' == 'None' ? '' : '{{ form.city.value }}';
    $("#id_city").replaceWith('<input id="id_city" value="'+ city + '" type="text" class="input-xlarge textinput textInput" name="city" maxlength="200">');  
  }

  var saved_select;
  $(document).ready(function() {
    saved_select = $("#id_city").parent().html();
    if ('TH' != '{{ form.country.value }}') {
      setup_foreign_city();
    }
  });

  $('.search-query').keypress(function(e) {
    if (e.which == 13) {
      e.preventDefault();
      search($('.search-query').val());
    }
  });
  
  $('#id_city').change(function() {
    search($("#id_city option:selected").text());
  });
  
  $('#id_country').change(function () {
    if ($("#id_country option:selected").text() == 'Thailand') {
      $("#id_city").replaceWith(saved_select);
    } else {
      setup_foreign_city();
    }
    search($("#id_country option:selected").text());
  });

  var geocoder = new google.maps.Geocoder();
  
  function search(query) {
    if (query.trim().length > 0) {        
      geocoder.geocode( {'address': query}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          var gmap = $('div.gmap:visible');
          var position = results[0].geometry.location;
          gmap.getMap().panTo(position);            
        } else {
          $('#alert_text').text('"'+query+'"' + ' not found')
          $('#alert_not_found').modal();
        }
      });
    }
  }
</script>

<script type="text/javascript">
    window.m_listener = {
        markerDragEnd: function(point) { 
          this.getMap().panTo(point.latLng);
        },
        mapIdle: function() {
          var gmap = $('div.gmap:visible');
          if (gmap.getMarkers()) {
            var marker = gmap.getMarkers()[0];
            gmap.removeMarkers();
            var center = gmap.getMap().getCenter();
            marker.setPosition(center);
            gmap.addMarkers([marker]);
            $('#id_latitude').val(center.lat().toFixed(5));
            $('#id_longitude').val(center.lng().toFixed(5));            
          }
        },
    };
</script>